module.exports = {
    "login": "Dsantacruz",
    "id": 8165329,
    "avatar_url": "https://avatars1.githubusercontent.com/u/8165329?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Dsantacruz",
    "html_url": "https://github.com/Dsantacruz",
    "followers_url": "https://api.github.com/users/Dsantacruz/followers",
    "following_url": "https://api.github.com/users/Dsantacruz/following{/other_user}",
    "gists_url": "https://api.github.com/users/Dsantacruz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Dsantacruz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Dsantacruz/subscriptions",
    "organizations_url": "https://api.github.com/users/Dsantacruz/orgs",
    "repos_url": "https://api.github.com/users/Dsantacruz/repos",
    "events_url": "https://api.github.com/users/Dsantacruz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Dsantacruz/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Diego Miguel Santa Cruz Mendezú",
    "company": "DSC",
    "blog": "http://programate.pe",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 33,
    "public_gists": 1,
    "followers": 1,
    "following": 1,
    "created_at": "2014-07-15T04:44:40Z",
    "updated_at": "2018-05-01T16:54:57Z"
  }